export const Mood = [
	{ mood: "Happy", color: "#FFD700" },
	{ mood: "Excited", color: "#FF4500" },
	{ mood: "Relaxed", color: "#00CED1" },
	{ mood: "Proud", color: "#800080" },
	{ mood: "Surprised", color: "#FFA500" },
	{ mood: "Content", color: "#00FF00" },
	{ mood: "Hopeful", color: "#00BFFF" },
	{ mood: "Neutral", color: "#808080" },
	{ mood: "Contempt", color: "#8B0000" },
	{ mood: "Confused", color: "#FFFF00" },
	{ mood: "Nervous", color: "#FF69B4" },
	{ mood: "Anxious", color: "#7FFF00" },
	{ mood: "Scared", color: "#0000FF" },
	{ mood: "Sad", color: "#000080" },
	{ mood: "Depressed", color: "#4B0082" },
	{ mood: "Angry", color: "#FF0000" },
	{ mood: "Disgusted", color: "#008080" },
	{ mood: "Shamed", color: "#800000" },
	{ mood: "Frustrated", color: "#FF6347" },
	{ mood: "Jealous", color: "#FFC0CB" },
	{ mood: "Other", color: "#808000" },
];
